services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: freeCode
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  test-postgres:
    image: postgres:17.4
    container_name: test_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: freeCode
    ports:
      - 5434:5432

volumes:
  pgdata:
